name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.24'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v $(go list ./... | grep -v '/test')

      - name: Run go vet
        run: go vet ./...

      - name: Check formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -s -l .
            exit 1
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build for current platform
        run: make build

      - name: Test binary
        run: ./mvx-binary version

      - name: Run integration tests
        run: |
          cd test
          go test -v -timeout=5m ./...

      - name: Run benchmarks
        run: |
          cd test
          go test -bench=. -benchtime=3s ./...

      - name: Build for all platforms
        run: make build-all

      - name: Generate checksums
        run: make checksums

      - name: Test wrapper
        run: |
          # Set a specific version to avoid GitHub API calls
          echo "dev" > .mvx/version
          ./mvx version

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mvx-binaries
          path: |
            dist/mvx-*
            dist/checksums.txt
          retention-days: 7

  wrapper-test:
    name: Test Wrapper
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build local binary
        run: make build

      - name: Test wrapper (Unix)
        if: runner.os != 'Windows'
        run: |
          # Ensure dev binary is available for wrapper
          mkdir -p ~/.mvx/dev
          cp mvx-binary ~/.mvx/dev/mvx
          chmod +x ~/.mvx/dev/mvx
          mkdir -p .mvx
          echo "dev" > .mvx/version
          ./mvx version

      - name: Test wrapper (Windows)
        if: runner.os == 'Windows'
        run: |
          # Ensure dev binary is available for wrapper
          New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.mvx\dev"
          Copy-Item "mvx-binary.exe" "$env:USERPROFILE\.mvx\dev\mvx.exe"
          New-Item -ItemType Directory -Force -Path ".mvx"
          echo "dev" | Out-File -FilePath ".mvx\version" -Encoding ascii
          .\mvx.cmd version
