name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup mvx
        run: ./mvx setup

      - name: Download dependencies
        run: ./mvx go mod download

      - name: Run tests
        run: ./mvx test

      - name: Run go vet
        run: ./mvx go vet ./...

      - name: Install golangci-lint
        run: ./mvx install-golangci-lint

      - name: Check formatting
        run: |
          GOROOT=$(./mvx go env GOROOT)
          unformatted=$($GOROOT/bin/gofmt -s -l .)
          if [ -n "$unformatted" ]; then
            echo "The following files are not formatted:"
            echo "$unformatted"
            exit 1
          fi

      - name: Run integration tests
        run: ./mvx test-integration

      - name: Run benchmarks
        run: ./mvx benchmark

      - name: Build for all platforms
        run: ./mvx build-all

      - name: Generate checksums
        run: ./mvx checksums

      - name: Test wrapper functionality
        run: |
          # Test that wrapper works with current version
          ./mvx version

      - name: Check website build
        run: |
          OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 1)
          REPO=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
          SITE_URL="https://${OWNER}.github.io"
          SITE_PATH="/${REPO}/"
          echo "SITE_URL=$SITE_URL" >> $GITHUB_ENV
          echo "SITE_PATH=$SITE_PATH" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY SITE_DIR=$SITE_DIR SITE_URL=$SITE_URL SITE_PATH=$SITE_PATH"
          # Build website to catch template syntax errors
          QUARKUS_ROQ_GENERATOR_BATCH=true ./mvx mvn clean package quarkus:run -f website -DskipTests --no-transfer-progress \
              -Dquarkus.http.root-path=$SITE_PATH \
              -Dsite.url=$SITE_URL

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mvx-binaries
          path: |
            dist/mvx-*
            dist/checksums.txt
          retention-days: 7
